<?php View::flash(); ?>

<div class="container shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
</div>

    <div class="container">
        <h2 class="page-header">Tus Fichajes <?php echo Session::get('nombre'); ?></h2>
        <div class="row">
            <div class='col-sm-6'>
                <?php echo DwForm::open(); ?>
                    <p>
                    	<?php echo DwForm::number('registro.usuario_id', array('class'=>'hidden'), Session::get('id'), NULL); ?>
                    </p>
                    <p>
                        <label>ELIGE MES:</label>
                        <div class="input-group date" id="id_3">
                            <label for="registro_entrada">entrada<span class="req">*</span></label>
                            <input id="registro_entrada" name="registro[entrada]" type="month" value="<?php date('Y-m'); ?>" class="form-control" onchange="this.value=this.value.toUpperCase()" required="required">
                            <span class="input-group-addon">
                            </span>
                        </div>
                    </p>
                    <p>
                    	<div class="row">
				<div class="form-actions">
				    <?php echo DwForm::send('Selecciona'); ?>
				</div>
			</div>
                    </p>
                <?php echo DwForm::close(); ?>
            </div>
        </div>
    </div>

