<?php View::flash(); ?>

<div class="container shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
</div>

    <div class="container">
        <h2 class="page-header">Hola <?php echo Session::get('nombre'); ?></h2>
        <div class="row">
            <div class='col-sm-6'>
                <form action="" method="post">
                    <p>
                        <label>ENTRADA:</label>
                        <div class="input-group date" id="id_0">
                            <input type="text" class="form-control" required/>
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                            </span>
                        </div>
                    </p>
                    <p>
                        <label>SALIDA:</label>
                        <div class="input-group date" id="id_1">
                            <input type="text" class="form-control"/>
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                            </span>
                        </div>
                    </p>
                    <p>
                    	<div class="row">
				<div class="form-actions">
				    <?php echo DwForm::send('fichar'); ?>
				</div>
			</div>
                    </p>
                    <p>
                    	<div class="row">
                    		<?php echo Session::get('id'); ?>
                    	</div>
                    </p>
                </form>
            </div>
        </div>
    </div>



